/**
 * Writes `docs/STATS.md` — every number the prose would otherwise hard-code.
 *
 *   npm run docs:stats
 *
 * Documentation rots at its figures. "616 of 2,424 fields", "a corpus of ~390
 * flows", "all 133 real blocks set it" — each was true when typed and silently
 * wrong a few commits later, and a reader has no way to tell which. Worse, one
 * of them turned into a worked example teaching something false.
 *
 * So the guides quote no derived number. They link here, and this file is
 * generated from the data itself. `tests/stats.test.ts` regenerates it and
 * fails if the committed copy differs, which makes a stale figure a build
 * failure rather than a thing someone has to notice.
 */

import { writeFileSync } from 'node:fs';
import { schema, CURRENT_VERSION } from '../src/flo/codec';
import { catalog } from '../src/flo/catalog';
import { blockCategory, editableFields, fieldKind } from '../src/flo/blocks';
import exprTable from '../src/data/exprtable.json';
import conventionsJson from '../src/data/conventions.json';
import requiredJson from '../src/data/required.json';

interface Tally {
  set: number;
  of: number;
}

const required = requiredJson as Record<string, string[]>;
const conventions = conventionsJson as {
  _provenance: { flows: number; minSamples: number };
  fields: Record<string, Record<string, Tally>>;
};
const rules = exprTable as unknown as Record<string, { kind: string; name?: string; op?: string }>;

/** Must match `CONVENTION_RATIO` in `src/flo/lint.ts`. */
const CONVENTION_RATIO = 0.95;

function table(rows: Array<[string, string | number]>, head: [string, string]): string {
  return [
    `| ${head[0]} | ${head[1]} |`,
    '| --- | ---: |',
    ...rows.map(([k, v]) => `| ${k} | ${typeof v === 'number' ? v.toLocaleString() : v} |`),
  ].join('\n');
}

function main(): void {
  const types = Object.values(schema);
  const ops = types.flatMap((t) => t.ops ?? []);
  const gated = ops.filter((o) => o.min !== undefined || o.max !== undefined);

  // Argument kinds, as `fieldKind()` reports them — the distinction §5 of the
  // agent guide is about, and the reason `op: 'obj'` is not "any expression".
  const kinds = new Map<string, number>();
  for (const tid of Object.keys(catalog)) {
    for (const f of editableFields(Number(tid))) {
      const k = fieldKind(Number(tid), f.name);
      kinds.set(k, (kinds.get(k) ?? 0) + 1);
    }
  }
  const argTotal = [...kinds.values()].reduce((a, b) => a + b, 0);

  const categories = new Map<string, number>();
  for (const e of Object.values(catalog)) {
    const c = blockCategory(e);
    categories.set(c, (categories.get(c) ?? 0) + 1);
  }

  const requiredFields = Object.values(required).reduce((a, f) => a + f.length, 0);
  const observedFields = Object.values(conventions.fields).reduce(
    (a, f) => a + Object.keys(f).length,
    0,
  );
  const conventionFields = Object.values(conventions.fields).reduce(
    (a, f) => a + Object.values(f).filter((t) => t.set > 0 && t.set / t.of >= CONVENTION_RATIO).length,
    0,
  );

  const funcs = new Set(
    Object.values(rules)
      .filter((r) => r.kind === 'func' && r.name)
      .map((r) => r.name!),
  );
  const operators = new Set(
    Object.values(rules)
      .filter((r) => (r.kind === 'binary' || r.kind === 'prefix') && r.op)
      .map((r) => r.op!),
  );

  const out = `<!-- Generated by tools/generate-stats.ts — do not edit. Run: npm run docs:stats -->

# Figures

Everything here is derived from the checked-in data, so the guides can link to
it instead of quoting numbers that go stale. Regenerate with \`npm run docs:stats\`;
\`tests/stats.test.ts\` fails if this file drifts from the data.

## The format

${table(
  [
    ['Format version written for new flows, and the newest readable', `v${CURRENT_VERSION}`],
    ['Object types in the wire schema (blocks, expressions, values)', types.length],
    ['Block types (statements)', Object.keys(catalog).length],
    ['Serialized fields across all types', ops.length],
    ['…of those, gated to a range of format versions', gated.length],
  ],
  ['', 'Count'],
)}

A version-gated field is skipped when saving a flow older than its gate, which
is why adding a modern block to an old flow can silently drop arguments.

## Block arguments, by \`fieldKind()\`

\`op: 'obj'\` does not mean "any expression": the app casts each argument as it
reads it, so the wrong node type throws inside Automate when the flow loads.
These are the kinds \`fieldKind(typeId, field)\` reports, over every editable
field of every block type.

${table(
  [...kinds].sort((a, b) => b[1] - a[1]).map(([k, n]) => [`\`${k}\``, n]),
  ['Kind', 'Fields'],
)}

${argTotal.toLocaleString()} editable fields in total. Anything other than
\`expression\` needs a specific node type, and ports are excluded here entirely —
they are connections, not arguments, so use \`connect()\`.

## Blocks by category

${table(
  [...categories].sort((a, b) => b[1] - a[1]).map(([c, n]) => [c, n]),
  ['Category', 'Blocks'],
)}

## Expressions

${table(
  [
    ['Expression node types', Object.keys(rules).length],
    ['Functions', funcs.size],
    ['Operators', operators.size],
  ],
  ['', 'Count'],
)}

## Lint rules

Two independent sources, described in [INTERNALS.md](INTERNALS.md#the-linter).

${table(
  [
    ['Block classes with a required-argument check in the app', Object.keys(required).length],
    ['Required-argument candidates found in the app’s code', requiredFields],
    ['Fields with enough corpus samples to say anything', observedFields],
    [`…set in ≥${Math.round(CONVENTION_RATIO * 100)}% of real blocks, so treated as expected`, conventionFields],
    ['Flows behind those counts', conventions._provenance.flows],
    ['Minimum samples before a field is considered at all', conventions._provenance.minSamples],
  ],
  ['', 'Count'],
)}
`;

  writeFileSync('docs/STATS.md', out);
  console.log(`docs/STATS.md — ${types.length} types, ${argTotal} fields, ${conventionFields} conventions`);
}

main();
