/**
 * Learns what the app itself always writes, from a corpus of real flows.
 *
 *   npx tsx tools/mine-conventions.ts <corpus-dir> > src/data/conventions.json
 *
 * `createBlock()` starts every argument at `null`, which is a legal "unset" in
 * the file format but is not always what Automate's own editor would have
 * written. `startActivity` on a dialog is the case that bit us: leave it null
 * and the block posts a notification instead of a window, so the fiber waits
 * for a tap that never comes. The flow parses, validates and round-trips
 * perfectly; it just hangs on the device.
 *
 * There is no way to derive that from the format — the field is genuinely
 * optional — so the evidence has to be the corpus: if several hundred flows by
 * several hundred authors all set a field, a block that leaves it empty is
 * probably a mistake.
 *
 * Two guards against inventing rules out of noise:
 *
 *   - a field needs MIN_SAMPLES observations before it is considered at all,
 *     so one author's habit cannot become a rule;
 *   - and it needs to be set in at least MIN_RATIO of them.
 *
 * The output records the counts, not just the verdict, so a warning can say
 * "297 of 298 flows set this" rather than asking to be trusted.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { schema } from '../src/flo/codec';
import { toModel } from '../src/flo/model';
import { editableFields } from '../src/flo/blocks';

/** Below this many observations a "convention" is one person's habit. */
const MIN_SAMPLES = 20;
/**
 * How near-universal a field has to be before its absence is worth mentioning.
 *
 * Calibrated against the case that motivated all this: `startActivity` on
 * `Dialog message` is set in 1540 of 1597 real blocks — 96.4%. A stricter bar
 * of 0.98 excluded it, which would have meant the linter staying silent on the
 * exact defect that hung a flow twice. The 57 exceptions are real (a flow can
 * legitimately want a notification instead of a window), so this is a genuine
 * convention with genuine exceptions, and the finding carries its own counts so
 * the reader can judge rather than take it on faith.
 */
const MIN_RATIO = 0.95;

interface Tally {
  set: number;
  of: number;
}

function main(): void {
  const dir = process.argv[2];
  if (!dir) {
    console.error('usage: mine-conventions.ts <corpus-dir>');
    process.exit(2);
  }

  const clsOf = new Map<number, string>();
  for (const [tid, rec] of Object.entries(schema)) {
    if (rec.cls) clsOf.set(Number(tid), rec.cls);
  }

  const tally = new Map<string, Map<string, Tally>>();
  const authorsSeen = new Set<string>();
  let flows = 0;

  for (const f of readdirSync(dir).filter((x) => x.toLowerCase().endsWith('.flo'))) {
    let model;
    try {
      model = toModel(new Uint8Array(readFileSync(join(dir, f))));
    } catch {
      continue; // audit-corpus.ts is where unreadable files get reported
    }
    flows++;
    authorsSeen.add(f);
    for (const b of model.blocks) {
      const cls = clsOf.get(b.typeId);
      if (!cls) continue;
      if (!tally.has(cls)) tally.set(cls, new Map());
      const fields = tally.get(cls)!;
      for (const op of editableFields(b.typeId)) {
        if (!fields.has(op.name)) fields.set(op.name, { set: 0, of: 0 });
        const t = fields.get(op.name)!;
        t.of++;
        if (b.raw[op.name] != null) t.set++;
      }
    }
  }

  const out: Record<string, Record<string, Tally>> = {};
  let observed = 0;
  let conventions = 0;
  for (const [cls, fields] of tally) {
    for (const [name, t] of fields) {
      // Everything with enough samples is emitted: the linter needs the "how
      // often is this left empty" number even for fields that are not a
      // convention, to decide how loudly to complain about a required one.
      if (t.of < MIN_SAMPLES) continue;
      (out[cls] ??= {})[name] = t;
      observed++;
      if (t.set / t.of >= MIN_RATIO && t.set > 0) conventions++;
    }
  }

  process.stdout.write(
    JSON.stringify(
      {
        _provenance: {
          flows,
          minSamples: MIN_SAMPLES,
          note:
            'generated by tools/mine-conventions.ts; do not hand-edit. Holds raw ' +
            'tallies for every field with enough samples — which of them count as ' +
            'a convention is decided by CONVENTION_RATIO in src/flo/lint.ts.',
        },
        fields: out,
      },
      null,
      1,
    ) + '\n',
  );
  console.error(
    `// ${observed} fields with >=${MIN_SAMPLES} samples from ${flows} flows; ` +
      `${conventions} meet the >=${MIN_RATIO} convention bar`,
  );
}

main();
